# Site settings
title: La Incendiaria
header-img: img/home-bg.jpg
email: lecturasmarxistas@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Un blog de pelis, cómics y libros con conciencia"
baseurl: "/OcioRevolucionario"
url: "https://granadaincendiaria.github.io"
twitter_username: OdeclasOnarres
github_username:  GranadaIncendiaria
email_username:  lecturasmarxistas@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
